<?hh // strict

enum ApiErrorType : int {
  EMPTY_USER_FIRST_NAME = 0x1;
  EMPTY_USER_LAST_NAME = 0x2;
  EMPTY_USER_EMAIL = 0x3;
  USER_EMAIL_MISSING_USERNAME_TOKEN = 0x4;
  USER_EMAIL_MISSING_DOMAIN_TOKEN = 0x5;
  EMPTY_USER_PASSWORD = 0x6;
  DUPLICATE_USER_EMAIL = 0x7;
}
