<?hh // strict

enum MethodErrorType : int {

  EMPTY_FIRST_NAME = 0x1;
  EMPTY_LAST_NAME = 0x2;
  EMPTY_EMAIL = 0x3;
  EMAIL_MISSING_USERNAME_TOKEN = 0x4;
  EMAIL_MISSING_DOMAIN_TOKEN = 0x5;
  EMAIL_EXTRANEOUS_USERNAME_TOKEN = 0x6;
  EMPTY_PASSWORD_HASH = 0x5;
}
